### ISSUE TITLE
Update to IntCal 2020 radiocarbon calibration curve?

### ISSUE THREAD

**Issue by wangyi91** [brenhinkeller/Chron.jl#18]
Hello, I am using your Chron package for a radiocarbon age-depth model. Thank you for writing it!
I just want to ask if it would be possible to include the new 14C calibration curve (2020) to the package? Here is the paper:
https://www.cambridge.org/core/journals/radiocarbon/article/intcal20-northern-hemisphere-radiocarbon-age-calibration-curve-055-cal-kbp/83257B63DC3AF9CFA6243F59D7503EFF

Thank you :)

**Comment by brenhinkeller** [comment]
Ah, sure thing! I’ll try to implement that in the next few days

**Comment by brenhinkeller** [comment]
This should do it -- let me know if you have any problems! Will be tagged and released as v0.4.0. This does also change the  the calibration data to be stored in a named tuple instead of a dictionary for better performance, so slight syntax changes, but the examples and notebooks are updated too.

**Comment by wangyi91** [comment]
Hi C., (should I just call you C. or Dr. Brenhin Keller?)

Thank you for updating the package! The newly added curve works well, but I do have two questions that I hope I could ask you for help:

I was trying the run an age-depth modelling using my 14C dates from a lake sediment core, and I was following your notebook of "age-depth model with non-Gaussian radiocarbon age constraints". However, when I tried running the model, namely:

# Run the stratigraphic MCMC model
(mdl, agedist, lldist) = StratMetropolis14C(smpl, config)

my agedist and lldist ended up being [NaN,…, NaN] and [-Inf,…, -Inf], even after I increased both config.nsteps and config.burnin by 10x. The same happened when I directly used your demonstration data in the notebook. May I ask if you think this is normal?

My second question is, where in the radiocarbon age-depth model can I find the specification for sedimentation rate/deposition rate model? I was using OxCal before for age-depth modelling and there I could specify the prior model of sedimentation rate. I wonder if I could set it up here in Chron.jl as well.

Sorry if my questions are ignorant, and thank you in advance for any advice!

Best,
Yi

**Comment by brenhinkeller** [comment]
Just Brenhin is fine! Want to email me an MWE and we can go from there?

So sedimentation rate in Chron.jl is actually constrained only by the data, not by any prior — so you can calculate it after the fact, but not specify it ahead of time. This is because Chron.jl is specialized for clastic, volcaniclastic, or volcanic stratigraphies where rate is characteristically inconstant, and not well represented by a single prior average.

**Comment by wangyi91** [comment]
Hi Brenhin,

Thank you for your previous reply! I was playing around with my radiocarbon data and chron.jl, but still cannot figure out a problem. May I ask you here? I attach my code and data so that you can replicate the problem. 

The problem I am encountering is: If I include my top-most sample, the log-likelihood (lldist) ends up being [-Inf,… Inf]. If I just exclude the top-most sample, the model works fine. 

The attached julia code is largely the same as yours, I just modified config.bounding as it seems to make a difference.

Also, I wanted to ask if it could be possible to enable multithreading for running the MCMC models? And would it be a interest of yours to incorporate prior distributions for the sedimentation rate, and/or make it possible for the model to identify outlier dates? You explained partially in your last email yet I still want to ask :) it’s totally okay if that’s not in your plan.

Thank you for your advice in advance.

Best,
Yi

**Comment by wangyi91** [comment]
Hi again Brenhin!

I think I know why I had the lldist being -Inf problem. The boundaries probably should not exceed where radiocarbon dating is applicable, i.e. around 1950. When I set config.bounding to a small number such as 0.001, the model works well.

I guess my questions for you now are just whether multithreading with the MCMC model would be possible, and whether you are interested in making Bayesian modelling possible for people working with dates from sediment cores :)

Thank you!

Best,
Yi

**Comment by brenhinkeller** [comment]
Oh great! I can think if there’s a better workaround in the future since setting bounding very small may have unintended consequences.

Multithreading will be hard, but sediment cores should already work!

**Comment by wangyi91** [comment]
Thank you Brenhin. May I ask another question? If I have both carbon dates and dates generated with other methods, is it possible to combine those data into one age-depth model, using Chron.jl? If yes, how would you recommend to do it?

Best,
Yi

**Comment by brenhinkeller** [comment]
Oh good question -- not easily at present, but I want to add that!
