### ISSUE TITLE
Sample import in Chron1.0StratOnly.jl

### ISSUE THREAD

**Issue by VauWennrich** [brenhinkeller/Chron.jl#28]
To avoid issues with the data/sample import, I would love to import the data directly from a csv or txt file. This would also make the re-import of updated data much easier. Is there an option to include this into the code?

Best, Volker

**Comment by brenhinkeller** [comment]
Thanks for opening the issue!

**Comment by brenhinkeller** [comment]
Ok, I think the following new "tabular input" example files should work for this:
https://github.com/brenhinkeller/Chron.jl/blob/main/examples/Chron1.0StratOnlyTabularInput.jl
https://github.com/brenhinkeller/Chron.jl/blob/main/examples/Chron1.0CoupledTabularInput.jl

Let me know if these do the trick!

**Comment by brenhinkeller** [comment]
Assuming no objections, I'll tentatively mark this issue as "completed", but feel free to reopen if these examples don't satisfy your use case!
